2019-03-13 00:02:19,163 ERROR: Exception on /explore [GET] [in /Users/taylor/.virtualenvs/microblog/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/taylor/.virtualenvs/microblog/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/taylor/.virtualenvs/microblog/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/taylor/.virtualenvs/microblog/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/taylor/.virtualenvs/microblog/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/taylor/.virtualenvs/microblog/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/taylor/.virtualenvs/microblog/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/taylor/.virtualenvs/microblog/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/taylor/Documents/Developer/flask-microblog/flask-web/app/routes.py", line 35, in explore
    page, app.config['POST_PER_PAGE'], False
KeyError: 'POST_PER_PAGE'
2019-03-13 00:02:59,334 ERROR: Exception on /index [GET] [in /Users/taylor/.virtualenvs/microblog/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/taylor/.virtualenvs/microblog/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/taylor/.virtualenvs/microblog/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/taylor/.virtualenvs/microblog/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/taylor/.virtualenvs/microblog/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/taylor/.virtualenvs/microblog/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/taylor/.virtualenvs/microblog/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/taylor/.virtualenvs/microblog/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/taylor/Documents/Developer/flask-microblog/flask-web/app/routes.py", line 25, in index
    page, app.config['POST_PER_PAGE'], False
KeyError: 'POST_PER_PAGE'
2019-03-13 00:03:02,218 ERROR: Exception on /index [GET] [in /Users/taylor/.virtualenvs/microblog/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/taylor/.virtualenvs/microblog/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/taylor/.virtualenvs/microblog/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/taylor/.virtualenvs/microblog/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/taylor/.virtualenvs/microblog/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/taylor/.virtualenvs/microblog/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/taylor/.virtualenvs/microblog/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/taylor/.virtualenvs/microblog/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/taylor/Documents/Developer/flask-microblog/flask-web/app/routes.py", line 25, in index
    page, app.config['POST_PER_PAGE'], False
KeyError: 'POST_PER_PAGE'
2019-03-13 00:05:45,403 ERROR: Exception on /explore [GET] [in /Users/taylor/.virtualenvs/microblog/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/taylor/.virtualenvs/microblog/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/taylor/.virtualenvs/microblog/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/taylor/.virtualenvs/microblog/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/taylor/.virtualenvs/microblog/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/taylor/.virtualenvs/microblog/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/taylor/.virtualenvs/microblog/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/taylor/.virtualenvs/microblog/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/taylor/Documents/Developer/flask-microblog/flask-web/app/routes.py", line 35, in explore
    page, app.config['POST_PER_PAGE'], False
KeyError: 'POST_PER_PAGE'
2019-03-13 00:05:47,491 ERROR: Exception on /explore [GET] [in /Users/taylor/.virtualenvs/microblog/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/taylor/.virtualenvs/microblog/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/taylor/.virtualenvs/microblog/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/taylor/.virtualenvs/microblog/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/taylor/.virtualenvs/microblog/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/taylor/.virtualenvs/microblog/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/taylor/.virtualenvs/microblog/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/taylor/.virtualenvs/microblog/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/taylor/Documents/Developer/flask-microblog/flask-web/app/routes.py", line 35, in explore
    page, app.config['POST_PER_PAGE'], False
KeyError: 'POST_PER_PAGE'
2019-03-13 00:05:50,446 ERROR: Exception on /index [GET] [in /Users/taylor/.virtualenvs/microblog/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/taylor/.virtualenvs/microblog/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/taylor/.virtualenvs/microblog/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/taylor/.virtualenvs/microblog/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/taylor/.virtualenvs/microblog/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/taylor/.virtualenvs/microblog/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/taylor/.virtualenvs/microblog/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/taylor/.virtualenvs/microblog/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/taylor/Documents/Developer/flask-microblog/flask-web/app/routes.py", line 25, in index
    page, app.config['POST_PER_PAGE'], False
KeyError: 'POST_PER_PAGE'
2019-03-13 00:06:38,785 INFO: Microblog startup [in /Users/taylor/Documents/Developer/flask-microblog/flask-web/app/__init__.py:46]
